### ISSUE TITLE
there is  an issue with ripple when , i click on  it ripples the entire parent of the elemnts

### ISSUE THREAD

**Issue by arezki1990** [PolymerElements/paper-ripple#29] opened 2015-07-19 04:22 UTC
ex: here in this code it ripple in iron-selector
```
<iron-selector multi selected-values='[0,2]'>
      <div> <h1>item  <paper-ripple id="ripple"></paper-ripple></h1>  </div>
      <div>Item 1</div>
      <div>Item 2</div>
      <div>Item 3</div>
      <div>Item 4</div>
    </iron-selector>
```

**Comment by ranjeet-choudhary** [comment] 2015-07-27 20:10
same here

**Comment by ebidel** [comment] 2015-09-30 22:38
Dupe of https://github.com/PolymerElements/paper-ripple/issues/31. The parent container of the ripple needs to be `position: relative`. I've added this to the docs to make it more clear.

**Closed by ebidel** 2015-09-30 22:38 UTC
