### ISSUE TITLE
Chrome 65 could break some Polymer 1.x and 2.x websites

### ISSUE THREAD

**Issue by chosh31** [PolymerElements/paper-ripple#106] opened 2017-12-12 07:42 UTC
[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.

- paper-ripple version: 1.0.10
- polymer dependency version 1.10.1 or newer for 1.x (current version: 1.1.0)

- link
   - https://www.polymer-project.org/blog/2017-10-18-upcoming-changes

**Comment by TimvdLippe** [comment] 2017-12-12 11:03
Duplicate of https://github.com/Polymer/polymer/issues/4867 Fixed in 1.x per https://github.com/Polymer/polymer/pull/4850

**Closed** 2017-12-12 18:28 UTC

**Comment by chosh31** [comment] 2017-12-13 01:32
However, paper-ripple v1 does not use the patched version.
- https://github.com/PolymerElements/paper-ripple/blob/1.x/bower.json#L22
